### ISSUE TITLE
node 0.5.X

### ISSUE THREAD

**Issue by kof** [chrisdickinson/tracejs#1]
Hi,

I have addedd tracejs as a dependency to my qunit module ... the new version will work with node@0.5.x only because of .fork method, right know I have troubles because tracejs needs node@0.4 and my module node@0.5.

https://github.com/kof/node-qunit/issues/30

I don't see anything specific in your implementation so I think you can just inc the node version for tracejs?

Thanks a lot.

Best,
Oleg

**Comment by chrisdickinson** [comment]
This should allow you to install tracejs on an 0.5.X node.

**Comment by kof** [comment]
thanks.
